### ISSUE TITLE
Is Psychology compatible with HelpTab?

### ISSUE THREAD

**Issue by mickdekkers** [rwpsychology/Psychology#13]
The description [on Steam](https://steamcommunity.com/sharedfiles/filedetails/?id=1220823511) mentions that Psychology isn't compatible with [HelpTab](https://steamcommunity.com/sharedfiles/filedetails/?id=946365802), but the compatibility section in the readme on GitHub doesn't mention HelpTab. Is it currently incompatible, or was the incompatibility resolved and the Steam description just needs to be updated? Steam doesn't display when the description was last updated, so it's hard to tell whether the GitHub readme is newer.

**Comment by rwpsychology** [comment]
I've been told by notfood that the incompatibility with HelpTab should be fixed. I'll remove the notice from all descriptions.
