### ISSUE TITLE
"{0} treatment failed" text formatting issue

### ISSUE THREAD

**Issue by beltsonata** [rwpsychology/Psychology#7]
Here's how it looks:

![pyromania-failed](https://user-images.githubusercontent.com/88738/34011818-4f6ad506-e109-11e7-8b0c-5b1837352258.png)

Game logs are here:

https://gist.github.com/HugsLibRecordKeeper/7fe3ffa281407c5d28a4f1bf399697f2

Let me know if you need anything else from my game files. Thanks! :)

**Comment by rwpsychology** [comment]
Can you please tell me which treatment you attempted that caused this glitch?

**Comment by beltsonata** [comment]
It was 'Treat Pyromania'.
